# Generated by Django 5.2.5 on 2025-08-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprehension_date', models.DateField(blank=True, null=True)),
                ('apprehension_state', models.CharField(blank=True, max_length=100, null=True)),
                ('apprehension_aor', models.CharField(blank=True, max_length=100, null=True)),
                ('final_program', models.CharField(blank=True, max_length=100, null=True)),
                ('final_program_group', models.CharField(blank=True, max_length=100, null=True)),
                ('apprehension_method', models.CharField(blank=True, max_length=100, null=True)),
                ('apprehension_criminality', models.CharField(blank=True, max_length=100, null=True)),
                ('case_status', models.CharField(blank=True, max_length=100, null=True)),
                ('case_category', models.CharField(blank=True, max_length=100, null=True)),
                ('departed_date', models.DateField(blank=True, null=True)),
                ('departure_country', models.CharField(blank=True, max_length=100, null=True)),
                ('final_order_yes_no', models.CharField(blank=True, max_length=10, null=True)),
                ('final_order_date', models.DateField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('citizenship_country', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('apprehension_site_landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('unique_identifier', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
