# Generated by Django 5.2.5 on 2025-09-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apprehension_date', models.DateField(blank=True, db_index=True, null=True)),
                ('apprehension_state', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('apprehension_aor', models.CharField(blank=True, max_length=100, null=True)),
                ('apprehension_criminality', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('citizenship_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('unique_identifier', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('age_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-apprehension_date', 'apprehension_state'],
                'indexes': [models.Index(fields=['apprehension_state', 'apprehension_date'], name='arrestdashb_apprehe_d0f21f_idx'), models.Index(fields=['age_category', 'apprehension_date'], name='arrestdashb_age_cat_d849b4_idx'), models.Index(fields=['gender', 'apprehension_date'], name='arrestdashb_gender_21c946_idx'), models.Index(fields=['citizenship_country', 'apprehension_date'], name='arrestdashb_citizen_ecf8fb_idx'), models.Index(fields=['apprehension_criminality', 'apprehension_date'], name='arrestdashb_apprehe_883085_idx'), models.Index(fields=['apprehension_state', 'age_category', 'apprehension_date'], name='arrestdashb_apprehe_df388a_idx'), models.Index(fields=['apprehension_state', 'gender', 'apprehension_date'], name='arrestdashb_apprehe_eb8817_idx'), models.Index(fields=['apprehension_state', 'citizenship_country', 'apprehension_date'], name='arrestdashb_apprehe_d8bd17_idx'), models.Index(fields=['age_category', 'gender', 'apprehension_date'], name='arrestdashb_age_cat_287621_idx'), models.Index(fields=['age_category', 'citizenship_country', 'apprehension_date'], name='arrestdashb_age_cat_1c4495_idx'), models.Index(fields=['apprehension_state'], name='arrestdashb_apprehe_574e38_idx'), models.Index(fields=['age_category'], name='arrestdashb_age_cat_ff84d5_idx'), models.Index(fields=['apprehension_date'], name='arrestdashb_apprehe_20dc1b_idx')],
            },
        ),
    ]
