# Generated by Django 5.2.5 on 2025-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrestdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrestrecord',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrestrecord',
            name='age_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
